# Generated by Django 6.0.7 on 2026-07-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
