# Generated by Django 6.0.7 on 2026-08-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_savedpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agreed_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agreed_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
