# Generated by Django 6.0.7 on 2026-08-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0002_voucher_voucherusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='address',
            field=models.TextField(default='Dhaka, Bangladesh'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='delivery_inside_dhaka',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='delivery_outside_dhaka',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='site_name',
            field=models.CharField(default='POBON MAKER', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='site_tagline',
            field=models.CharField(default='Engineering Components & Maker Hub Bangladesh', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_email',
            field=models.EmailField(default='support@pabonmaker.com', max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_phone',
            field=models.CharField(default='+880 1700-000000', max_length=20),
        ),
    ]
