# Generated by Django 6.0.7 on 2026-08-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0003_systemsettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='privacy_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
