# Generated by Django 6.0.7 on 2026-07-31 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_icon_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
